### ISSUE TITLE
[Bounty] Insufficient check to prevent transferral of locked tokens from the DAO

### ISSUE THREAD

**Issue by adamkolar** [ProjectWyvern/wyvern-ethereum#4]
On line 341 of DelegatedShareholderAssociation.sol there's this check:
```javascript
            /* Prevent the DAO from sending the locked shares tokens (and thus potentially being unable to release locked tokens to delegating shareholders). */
            require(ERC20(sharesTokenAddress).balanceOf(address(this)) >= totalLockedTokens);
```
this won't catch a call of approve ERC20 function, because that call doesn't immediately decrease balance. So transferral of tokens in ownership of the DAO contract is still possible, despite the intention to prevent it.

**Comment by protinam** [comment]
This is accurate, that check only prevents explicit transfer calls.

Potentially worse, were the DAO to mistakenly approve a cumulative total of token withdrawals higher than the intended available balance (balance less locked tokens), and those token withdrawals were carried out, *no* proposals would be able to be executed, even ones that didn't transfer any tokens at all.

Conceivably it would be possible to track the cumulative amount of approved tokens and require that the available balances less the cumulative approved token amount be less than the locked token balance; however, I do not believe the ERC20 specification provisions a way to do that directly, we'd have to modify the token contract substantially.

Do you see a better way to fix this? Otherwise, I think we'll just cut this line - it will be true in any case that a delegator locking their tokens would be able to see upcoming proposals before their execution, and withdraw tokens prior to proposal execution if the proposal would have spent locked tokens.

**Comment by adamkolar** [comment]
How about preventing all calls to the token contract in the proposals? I don't see legitimate use case for it.

**Comment by protinam** [comment]
We definitely want to allow calls to the token contract - the DAO will receive about 7.5% of the initial token supply, to be used according to the intent of the shareholders, possibly for funding bounties, paying contractors, etc.

**Comment by adamkolar** [comment]
Ok, then other way to do it would be to store the locked tokens in a separate contract away from the DAO funds, this contract would be controlled by the DAO contract, but not callable in proposals.

**Comment by adamkolar** [comment]
I think combining delegated tokens with the tokens in the ownership of the DAO is messy a can lead to a number of unforeseen problems, separating the tokens seems like a much better way to go about it and should result in a cleaner code with less checks to cover special cases, it should for example also solve this issue by default: https://github.com/ProjectWyvern/wyvern-ethereum/issues/5

**Comment by protinam** [comment]
Yes, I agree, I'm writing up an implementation now (but we'll pay both issues separately).

**Comment by protinam** [comment]
Tentatively addressed by 2c88f6789858ecf6151bf09eb6db8e7c191c3a93 - I'll write a few more test cases but let me know what you think or if you see any further issues.

**Comment by protinam** [comment]
(And obviously, we'll pay for this)

**Comment by adamkolar** [comment]
It's late over here, I'm about to go to bed. I'll check it out tomorrow and get back to you.

**Comment by protinam** [comment]
Additional tests added in edb09d241bafc14736fe618198b04cae61134973.

**Comment by adamkolar** [comment]
I went over the changes and it looks good.

**Comment by protinam** [comment]
Thanks!

We rate this as `High`; we'll pay $1000. Please provide an Ethereum address.

**Comment by adamkolar** [comment]
My address: 0x6eB4e59aB22ac614cf800D3CB6d086C19900e606 (https://etherscan.io/address/adamkolar.eth)

**Comment by protinam** [comment]
Paid (combined with #5) - https://etherscan.io/tx/0xb0a60c8e12757af5d9821fdb9228aa9a1d6079de479d4fb81b429ea55c097ed9.

Issue no longer eligible for bounty submission.
