### ISSUE TITLE
[Bounty] DAO can delegate locked tokens

### ISSUE THREAD

**Issue by adamkolar** [ProjectWyvern/wyvern-ethereum#5]
Currently, because DAO can call approve function on the token and can call itself, it can delegate locked tokens to some address, effectively creating new votes from thin air, I think that should be prevented. 
Furthermore, if user withdrawal of tokens lowers the amount of locked tokens under the amount that the DAO delegated, the delegation can't be reversed.

**Comment by protinam** [comment]
I agree, that is strange, although it would require explicit intentional action from DAO shareholders to make the first call.

Nonetheless, we'll block self-delegation.

As far as I can reason, it does not give any particular voters undue influence, as the DAO would have to execute a proposal in order to call `vote` on itself, but if you have a specific example in mind walk me through it.

Rated as Medium pending any more severe attacks if you think this would have enabled them.

**Comment by protinam** [comment]
Final rating: `Medium`. We'll pay $200, please provide an Ethereum address.

**Comment by adamkolar** [comment]
My address: 0x6eB4e59aB22ac614cf800D3CB6d086C19900e606 (https://etherscan.io/address/adamkolar.eth)

**Comment by protinam** [comment]
Paid (combined with #4) - https://etherscan.io/tx/0xb0a60c8e12757af5d9821fdb9228aa9a1d6079de479d4fb81b429ea55c097ed9.

Issue no longer eligible for bounty submission.
